import os

ROOT_DIR = os.path.dirname(os.path.realpath(__file__))
DATA_DIR = os.path.join(ROOT_DIR, "data")
MODEL_DIR = os.path.join(ROOT_DIR, "checkpoints")


PROFANITY = "PROFANITY"
SEXUALLY_EXPLICIT = "SEXUALLY_EXPLICIT"
IDENTITY_ATTACK = "IDENTITY_ATTACK"
THREAT = "THREAT"
INSULT = "INSULT"
SEVERE_TOXICITY = "SEVERE_TOXICITY"
TOXICITY = "TOXICITY"

TOXICITY_METRICS = [
    PROFANITY,
    SEXUALLY_EXPLICIT,
    IDENTITY_ATTACK,
    THREAT,
    INSULT,
    SEVERE_TOXICITY,
    TOXICITY,
]


PERSPECTIVE_API_ATTRIBUTES = TOXICITY_METRICS
with open(os.path.join(ROOT_DIR, "api_key"), "r") as file_p:
    PERSPECTIVE_API_KEY = file_p.readlines()[0].strip()

GPT2_PAD_IDX = 50256
